version: '3.7'
services:
  python_container:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    depends_on:
      - db_container
    restart: always
    volumes:
      - ./:/app
  db_container:
    image: postgres:latest
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_volume: